### ISSUE TITLE
Skip updating the opam-repository?

### ISSUE THREAD

**Issue by MisterDA** [kit-ty-kate/opam-grep#5]
I'm not sure if opam-grep updates the opam-repository before it starts grepping or not during
```
[Info] Getting the list of all known opam packages..
[Info] Fetching and grepping using rg..
```
but if I'm launching a few times opam-grep I don't need to have it update the opam-repository, which can also be quite slow on slow connections.
Could you add a flag to skip updating the opam-repository, if that's the case?
Thanks!

**Comment by kit-ty-kate** [comment]
opam-grep doesn't update the opam-repository. The only commands ran are:
- opam list
- opam source
- opam show

Now what you see as taking some time might be the `opam list` + `opam show` part. The latter is currently used in a loop on all the packages returned by the former.
Once opam 2.3 is out, we should be able to instead use just one `opam list` with `--latests-only` which would simplify and speedup all this (https://github.com/ocaml/opam/pull/5375)

**Comment by MisterDA** [comment]
Thanks for the explanation!
